name: Tests
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - "README.md"

  push:
    branches: ["main", "release/*"]
    paths-ignore:
      - "README.md"

  workflow_dispatch:
    inputs:
      branch_commit_or_ref:
        description: "Run this workflow in what branch/commit?"
        required: true
        type: string
        default: main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.branch_commit_or_ref || '' }}

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Run Build
        run: go build -v .

      - name: Run Tests
        run: go test ./internal/sqlparse/ -v -count=1

  test:
    name: Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.branch_commit_or_ref || '' }}

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Install coverage tools
        run: |
          go install github.com/wadey/gocovmerge@latest
          go install github.com/boumenot/gocover-cobertura@latest

      - name: Run unit tests with coverage
        run: go test ./internal/sqlparse/ -v -count=1 -coverprofile=sqlparse.cover -covermode=atomic

      - name: Run Acceptance Tests with coverage
        env:
          TF_ACC: 1
        run: go test ./internal/provider/ -v -count=1 -timeout 20m -coverprofile=provider.cover -covermode=atomic

      - name: Merge and convert code coverage
        run: |
          gocovmerge sqlparse.cover provider.cover > cover.out
          gocover-cobertura < cover.out > coverage.xml
          go tool cover -func=cover.out -o coverage.log


      - name: Run Documentation Tests
        run: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs validate --provider-name bqutils

## End of file -------------------------------------------------------------------- ##
